<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="LabApi">
        <HintPath>..\..\..\Рабочий стол\QurryСсылки\LabApi.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\Рабочий стол\dependsQueryRework\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>